### ISSUE TITLE
Enable email notification when an alarm is triggered

### ISSUE THREAD

**Issue by yipengsun** [umd-lhcb/NeoBurnIn#10]
@ZishuoYang @manuelfs The email notification is already supported, and we just need to enable it.

We need username and password of an email account. Can we use the `lhcb@physics.umd.edu` account?

Here's an example on how to enable it in the configuration file:
```yaml
log:
    filename: logs/test_temp_ctrl_client.log
    maxSize: 100 MB
    backupCount: 10
    fromaddr: example@example.com
    toaddrs: 1@example.com,2@example.com
    credentials: some_passwd
    interval: 1 MIN
```
